name: Run AQI analysis hourly

on:
  schedule:
    - cron: "5 * * * *"   # phút thứ 05 mỗi giờ
  workflow_dispatch: {}
  push:
    paths:
      - "analysis.ipynb"
      - ".github/workflows/analysis.yml"
      - "result/**"
      - "requirements.txt"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas numpy ipykernel nbconvert
          fi

      - name: Execute analysis.ipynb -> analysis_output.ipynb
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute analysis.ipynb \
            --output analysis_output.ipynb \
            --ExecutePreprocessor.kernel_name=python3 \
            --ExecutePreprocessor.timeout=1800

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add analysis_output.ipynb result_summary/ || true

          if ! git diff --cached --quiet; then
            git commit -m "chore(aqi): auto update $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          else
            echo "No changes to commit."
          fi
