name: analysis-update

on:
  schedule:
    - cron: '5 * * * *'     # chạy mỗi giờ, phút thứ 05 (đợi crawl/merge xong)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || github.token }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Chạy notebook cũ, chỉ khác là nó đọc data từ /result
      - name: Execute analysis notebook
        run: |
          papermill detection/analysis.ipynb detection/detection_output.ipynb

      # Commit các file kết quả do notebook xuất ra (csv/png) + notebook output
      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add detection/detection_output.ipynb
          git add reports/latest/* || true
          git add reports/latest/charts/* || true
          git commit -m "auto: refresh analysis $(date -u +'%Y-%m-%dT%H:%MZ')" || echo "nothing to commit"
          git push
