name: analysis-update

on:
  schedule:
    - cron: '5 * * * *'   # chạy mỗi giờ phút thứ 05 (đợi crawl/merge xong)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || github.token }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # dự phòng nếu thiếu:
          # pip install papermill ipykernel

      - name: Execute analysis notebook
        run: |
          papermill detection/analysis.ipynb detection/analysis_output.ipynb \
            -p RESULT_DIR "$(pwd)/result" \
            -p OUT_DIR    "$(pwd)/detection"

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add detection/*.csv detection/*.png || true
          git add detection/analysis_output.ipynb || true
          git commit -m "auto: refresh analysis $(date -u +'%Y-%m-%dT%H:%MZ')" || echo "nothing to commit"
          git push
