name: Run AQI Analysis

on:
  schedule:
    - cron: "5 * * * *" # chạy mỗi giờ (phút 05)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || github.token }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Jupyter + nbconvert bắt buộc để execute notebook
          pip install jupyter "nbconvert[execute]" nbclient ipykernel
          # Lib tối thiểu cho notebook AQI (thêm nếu bạn cần)
          pip install pandas numpy matplotlib

      # Nếu analysis.ipynb ở ROOT, giữ nguyên. Nếu ở thư mục khác, đổi working-directory.
      - name: Execute analysis.ipynb -> analysis_output.ipynb
        run: |
          jupyter nbconvert \
            --to notebook \
            --execute analysis.ipynb \
            --output analysis_output.ipynb \
            --ExecutePreprocessor.kernel_name=python3 \
            --ExecutePreprocessor.timeout=1800

      - name: Commit & Push Results (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config core.autocrlf false

          # Track output notebook + thư mục kết quả tóm tắt
          git add analysis_output.ipynb result_summary/ 2>/dev/null || true

          if ! git diff --cached --quiet; then
            git commit -m "Auto-run AQI analysis: update results & notebook"
            # Kéo về trước để tránh lỗi non-fast-forward khi có push khác
            git pull --rebase --autostash origin ${{ github.ref_name }} || true
            git push
          else
            echo "No analysis changes to commit."
          fi
