name: Merge AQI Data for All Cities

on:
  schedule:
    - cron: '5 * * * *'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  merge-aqi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || github.token }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Merge monthly CSVs for all cities
        run: |
          python merge_all_cities.py

      - name: Commit & push if changed
        shell: bash
        run: |
          set -euo pipefail
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global core.autocrlf false
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Update merge AQI CSVs for all cities"
            git push
          else
            echo "No changes to commit."
          fi
